

$latex = 'latex -file-line-error -synctex=1 %O %S';

# Force pdflatex to use xelatex
$pdflatex = 'xelatex -file-line-error -synctex=1 %O %S';
$xelatex  = 'xelatex -file-line-error -synctex=1 %O %S';

$latex_silent_switch   = "-interaction=batchmode";
$xelatex_silent_switch = "-interaction=batchmode";

$pdf_mode = 5; # XeLaTeX

$pdf_previewer = 'xdg-open %O %S';

$bibtex_use = 2;


# --------------------------------------------------
# Build in RAM
# --------------------------------------------------

use Sys::Hostname;
use Cwd qw(abs_path);
use Digest::MD5 qw(md5_hex);
use File::Copy qw(copy);
use File::Path qw(make_path);
use File::Basename qw(basename);

my $project  = abs_path('.');
my $hash     = md5_hex($project);
my $ramdir   = "/dev/shm/latexmk-$ENV{USER}/$hash";

# --------------------------------------------------
# Configurable variables
# --------------------------------------------------
my @figdirs = qw(
    figures
    pictures
    figs
);

my $texmfbibdir = "$ENV{HOME}/texmf/bibtex/bib";

my @bibfiles = (
    glob("$texmfbibdir/*.bib"),
    glob("*.bib"),
);


# --------------------------------------------------
# Cache texmf bibliography files in RAM
# --------------------------------------------------

my %bibfiles;

# Make and Protect the ram folder
make_path($ramdir, { mode => 0700 }) unless -d $ramdir;

# TeXMF files first
foreach my $src (glob("$texmfbibdir/*.bib")) {
    $bibfiles{basename($src)} = $src;
}

# Project-local files override TeXMF files
foreach my $src (glob("*.bib")) {
    $bibfiles{basename($src)} = $src;
}

foreach my $bib (keys %bibfiles) {
    my $src = $bibfiles{$bib};
    my $dst = "$ramdir/$bib";

    if (!-e $dst || (stat($src))[9] > (stat($dst))[9]) {
        print "Latexmk: caching $src -> $dst\n";

        copy($src, $dst)
            or die "Cannot copy $src to $dst: $!";

        my @st = stat($src);
        utime($st[8], $st[9], $dst);
    }
}

# --------------------------------------------------
# Cache figures/ folder in RAM
# --------------------------------------------------

# Cache figures into ram

foreach my $dir (@figdirs) {
    if (-d $dir) {
        system(
            "rsync", "-av", "--delete",
            "$dir/", "$ramdir/$dir/"
        );
    }
}

# --------------------------------------------------
# AUX, OUT files in RAM
# --------------------------------------------------
# Everything generated during compilation goes to RAM
$aux_dir = $ramdir;
$out_dir = $ramdir;

# Only final PDF/synctex are copied back after latexmk has converged
$out2_dir = '.';

# Important when aux_dir is outside the project tree
$bibtex_fudge = 1;
