
$latex = 'latex -file-line-error  %O %S';

# Force pdflatex to use xelatex
$pdflatex = 'xelatex -file-line-error  %O %S';
$xelatex = 'xelatex -file-line-error %O %S';

$latex_silent_switch   = "-interaction=batchmode";
$xelatex_silent_switch = "-interaction=batchmode";

$pdf_mode = 5; # LuaLaTeX(4) is slower than XeLaTeX(5)

$pdf_previewer = 'xdg-open %O %S';

$bibtex_use = 2;  # Run biber or bibtex if needed, bbl  files  are  always treated as regeneratable, and are deleted in a cleanup.

# Save intermediate files to different folder, not compatible with "minted" nor auctex
use Sys::Hostname;
my $hostname = hostname;
$aux_dir = "auto/$hostname";
# Do not cd into aux_dir for BibTeX; keeps relative \bibliography paths stable.
$bibtex_fudge = 0;

# Maximum runs of xelatex reached without getting stable files
#$max_repeat = 10;

# biber by default assumes we're running a more modern compiler like XeLaTeX or LuaTeX on
# the backend, which isn't true in arXiv submission
#$biber = 'biber --output-safechars %O %S';
